#  Question 1 :

Write a Python script to check the dimension of array given below:
[[[[(1.2),(4.5,6.2,2.3),(2.4,8.7)]]]]
 

In [1]:
import numpy as np

In [2]:
q1 = np.array([[[[(1.2),(4.5,6.2,2.3),(2.4,8.7)]]]],dtype=object)
print(q1.ndim)

4


# Question 2 :

Write a python script to find the logarithmic value of array given below: [1,3,6,2**4]


In [3]:
q2 = np.array([1,3,6,2**4])
print(np.log(q2))

[0.         1.09861229 1.79175947 2.77258872]


# Question 3

Write a python script to print 2.4 and 5.23 using slicing method in the given array: ([(1,2.4,7),(4,5.23,6.0),(17,23,9)]) 


In [4]:
q3 = np.array ([(1,2.4,7),(4,5.23,6.0),(17,23,9)])
print(q3[0:1,1])

[2.4]


# Question 4
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [5]:
q4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

q4_1 = q4.reshape(2, 3, 2)

print(q4_1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Question 5
Print the scalar values of given array: ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [6]:
q5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
q5_1 = q5.reshape(-1)
for i in range(len(q5_1)):
    print(q5_1[i])

1
2
3
4
5
6
7
8
9
10
11
12
